build:
	R CMD build --configure-args='--with-jplex=/afs/ir.stanford.edu/users/c/h/chakj/plex3/jplex.jar' PLEX3
check:
	R CMD check PLEX3
install:
	R CMD INSTALL -l ~/Rbin/ --configure-args='--with-jplex=/afs/ir.stanford.edu/users/c/h/chakj/plex3/jplex.jar' PLEX3
